---
title: "99-publish"
date: "Compiled at `r format(Sys.time(), '%Y-%m-%d %H:%M:%S', tz = 'UTC')` UTC"
output: github_document
params:
  name: "99-publish" # change if you rename file
---

```{r here, message=FALSE}
here::i_am(paste0(params$name, ".Rmd"), uuid = "da2d40a5-231f-404f-96ad-f86272f58669")
```

The purpose of this document is ...

```{r packages}
library("conflicted")
```

```{r directories}
# create or *empty* the target directory, used to write this file's data: 
projthis::proj_create_dir_target(params$name, clean = TRUE)

# function to get path to target directory: path_target("sample.csv")
path_target <- projthis::proj_path_target(params$name)

# function to get path to previous data: path_source("00-import", "sample.csv")
path_source <- projthis::proj_path_source(params$name)
```

## Tasks

This will be just copying files from earlier in the workflow:

```{r}
fs::file_copy(
  path_source("01-county-metadata", "iowa_county_meta.csv"),
  path_target()
)
```


```{r}
fs::file_copy(
  path_source("03-merge", "iowa_county_data.csv"),
  path_target()
)
```


```{r}
fs::file_copy(
  path_source("04-explore", "iowa_county_cases_week_current.csv"),
  path_target()
)
```

```{r}
fs::file_copy(
  path_source("04-explore", "iowa_cases_week.csv"),
  path_target()
)
```

```{r}
fs::file_copy(
  path_source("04-explore", "iowa_cases.png"),
  path_target()
)
```

```{r}
fs::file_copy(
  path_source("04-explore", "iowa_change.png"),
  path_target()
)
```

## Files written

These files have been written to the target directory, ```r paste0("data/", params$name)```:

```{r list-files-target}
projthis::proj_dir_info(path_target())
```
